projeto/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
# urlpatterns são as regras de caminhos que temos dentro do site, path recebe (caminho, onde vai abrir, nome exibido)

urlpatterns = [
    #Ppath('') esta dizendo que quando nenhum slug for informado ele vai cair nessa pag como defaul.
    #as_view() é quem é responsavel pelas chamadas da URL quando estamos trabalhando no modelo de Class (oque estamos afaznedo aqui)
    path('', views.PostListView.as_view(), name="list"),
    path("<slug:slug>/", views.PostDetailView.as_view(), name="detail")
]

projeto/projeto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls', namespace="polls")),
    path('admin/', admin.site.urls),
]

projeto/polls/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class polls(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE) 
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created",)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"slug":self.slug})

projeto/polls/views.py
from django.views.generic import DetailView, ListView
from .models import polls
# view, genericas feitas por class.

class PostListView(ListView):
    model = polls

class PostDetailView(DetailView):
    model = polls

projeto/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title> {% block title %}{% endblock %}</title>
    <link href="{% static 'css/poll.css' %}" rel= "stylesheet">
</head>
<body>
    <header>
        <h1>Blog fofo</h1>
    </header>
    <main>
        {% block content %} 
        {% endblock %}

    </main>
</body>
</html>

projeto/polls/templates/polls/post_list.html
{% extends "polls/base.html" %}

{% block title %} Meu Blog {% endblock %}


{% block content %}
    {% for post in polls_list %}
        <article>
            <h2> {{ post.title }}</h2>
            <p class="date">
                Publicidade em {{ polls.created }} por {{ polls.author }}
            </p>
            {{ post.body|linebreaks|truncatewords: 10}}
        </article>
{% endblock %}